name: filmax
description: filmax

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  google_fonts: ^2.1.0
  provider: ^5.0.0
  sqflite: ^2.0.0+3
  intl: ^0.17.0
  mockito: ^5.0.12
  rxdart: ^0.27.1
  video_player: ^2.1.12
  chewie: ^1.2.2
  flutter_shine: ^0.0.5
  dio: ^4.0.0

  android_alarm_manager: ^2.0.2
  flutter_local_notifications: ^6.0.0
  webview_flutter: ^2.0.10
  image_picker: ^0.8.2

  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^7.0.1
  # Value equality
  equatable: ^2.0.3
  # Functional programming thingies
  dartz: ^0.9.2
  # Remote API
  connectivity: ^3.0.6
  http: ^0.13.3
  data_connection_checker: ^0.3.4
  # Local cache
  shared_preferences: ^2.0.6
  # map
  google_maps_flutter: ^2.0.6
  permission_handler: ^8.1.4+1
  geolocator: ^7.3.1
  geocoder: ^0.2.1
  geocoding: ^2.0.0
  location: ^4.3.0

#  connectivity: ^3.0.3
#  http: ^0.13.0
#  shared_preferences: ^2.0.5
#  #  dio: ^1.0.0
#
#  #  youtube_player_flutter: ^8.0.0
#  #  youtube_player_flutter: ^7.0.0+7
#
#  #  chewie: ^1.0.0
#  #  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/logo_movieku.png

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_movieku.png"